### ISSUE TITLE
Error: Missing Data alors que toutes les données requises sont envoyés

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#13]
Le serveur renvoie Missing Data lors de du post d'une activité alors que toutes les données requises sont envoyés.
Endpoint : post /activity

**Comment by Kez0X** [comment]
l'erreur missing data ne vient pas de moi, test des données ok de mon côté, les erreurs sql ont été réglés. Middleware à toi de vérifier les données envoyer, test check
