### ISSUE TITLE
La liste d'activité renvoyé par le serveur sur un jour précis est vide alors que des activités existe dans la bdd

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#15]
ENDPOINT : GET /user/activities

Le serveur renvoie une liste vide pour les activités du jour demandé alors que la base de données contient bel et bien une liste d'activités.

Source probable de l'erreur dans le fichier user.js des routes de l'api :
```const sqlQuery = `SELECT * FROM activities WHERE userID = ? AND activityTimestamp = ? ;``` (L319)
Le champ activityTimestamp prend en compte l'heure et le les minutes, la ou nous souhaitons prendre toute une journée, quelque soit l'heure et la minute.

**Comment by Kez0X** [comment]
Pour régler ce problème, j'ai utilisé la fonction DATE() de mysql, peut import le timestamp que le client enverra on regardera uniquement si la date correspond bien.

Problème réglé...
