### ISSUE TITLE
Aucun enregistrement de l'activité lié lors de l'envoi d'un post

### ISSUE THREAD

**Issue by Vrock691** [VLD-dev-team/Social-Co2#38]
ENDPOINT : POST /social/post

body de la requette:
```
{"postID":0,"userID":"e90oW5bPEXQQak49uuXosoi4dxE2","postCreatedAt":"2024-04-26T
13:00:58.144","postType":"activite","postTextContent":"J'ai effectué(e) cet
activité : Repas de
10:56","postLinkedActivity":{"activityType":"meal","activityName":"Repas de
10:56","activityTimestamp":"2024-04-25T08:56:20.000Z","activityID":54,"userID":"
e90oW5bPEXQQak49uuXosoi4dxE2","activityCO2Impact":5},"activityid":54}
```

Ligne enregistré dans la base de donnée:
`|     43 | e90oW5bPEXQQak49uuXosoi4dxE2 | J'ai effectué(e) cet activité : Repas de 10:56   | NULL                | {}                 |               0 | 2024-04-26 12:48:50 |                  0 | activite |`

**Comment by Kez0X** [comment]
Issue régler problème liée au JSON.strinfy
